src/Presentation/SmartStore.Web/Models/Catalog/BackInStockSubscribeModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class BackInStockSubscribeModel : ModelBase
    {
        public int ProductId { get; set; }
        public LocalizedValue<string> ProductName { get; set; }
        public string ProductSeName { get; set; }

        public bool IsCurrentCustomerRegistered { get; set; }
        public bool SubscriptionAllowed { get; set; }
        public bool AlreadySubscribed { get; set; }

        public int MaximumBackInStockSubscriptions { get; set; }
        public int CurrentNumberOfBackInStockSubscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/CategoryModel.cs
using System.Collections.Generic;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Services.Localization;
using SmartStore.Services.Search;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.UI;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Search;

namespace SmartStore.Web.Models.Catalog
{
    public partial class CategoryModel : EntityModelBase, ISearchResultModel
    {
        public CategoryModel()
        {
			PictureModel = new PictureModel();
            SubCategories = new List<SubCategoryModel>();
        }

		public CatalogSearchResult SearchResult
		{
			get;
			set;
		}

		public LocalizedValue<string> Name { get; set; }
		public LocalizedValue<string> FullName { get; set; }
        public LocalizedValue<string> Description { get; set; }
		public LocalizedValue<string> BottomDescription { get; set; }
        public LocalizedValue<string> MetaKeywords { get; set; }
        public LocalizedValue<string> MetaDescription { get; set; }
        public LocalizedValue<string> MetaTitle { get; set; }
        public string SeName { get; set; }
        
        public PictureModel PictureModel { get; set; }

        public bool DisplayCategoryBreadcrumb { get; set; }

		public SubCategoryDisplayType SubCategoryDisplayType { get; set; }
        
        public IList<SubCategoryModel> SubCategories { get; set; }

        public ProductSummaryModel FeaturedProducts { get; set; }
        public ProductSummaryModel Products { get; set; }
        

		#region Nested Classes

        public partial class SubCategoryModel : EntityModelBase
        {
            public SubCategoryModel()
            {
                PictureModel = new PictureModel();
            }

            public LocalizedValue<string> Name { get; set; }
            public string SeName { get; set; }
            public PictureModel PictureModel { get; set; }
        }

		#endregion
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/IListActions.cs
using System;
using System.Collections.Generic;
using SmartStore.Core;
using SmartStore.Core.Domain.Catalog;

namespace SmartStore.Web.Models.Catalog
{
	public interface IListActions
	{
		ProductSummaryViewMode ViewMode { get; }
		GridColumnSpan GridColumnSpan { get; }
		bool AllowViewModeChanging { get; }

		bool AllowFiltering { get; }

		bool AllowSorting { get; }
		int? CurrentSortOrder { get; }
		string CurrentSortOrderName { get; }
		IDictionary<int, string> AvailableSortOptions { get; }

		IPageable PagedList { get; }
		IEnumerable<int> AvailablePageSizes { get; }
	}
}

src/Presentation/SmartStore.Web/Models/Catalog/IQuantityInput.cs
using SmartStore.Core.Domain.Catalog;
using SmartStore.Services.Localization;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SmartStore.Web.Models.Catalog
{
	public interface IQuantityInput
	{
		int EnteredQuantity { get; }
		int MinOrderAmount { get; }
		int MaxOrderAmount { get; }
        int QuantityStep { get; }
		LocalizedValue<string> QuantityUnitName { get; }
		List<SelectListItem> AllowedQuantities { get; }
        QuantityControlType QuantiyControlType { get; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ManufacturerModel.cs
using System.Collections.Generic;
using SmartStore.Services.Localization;
using SmartStore.Services.Search;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Search;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ManufacturerModel : EntityModelBase, ISearchResultModel
	{
        public ManufacturerModel()
        {
            PictureModel = new PictureModel();
        }

        public LocalizedValue<string> Name { get; set; }
        public LocalizedValue<string> Description { get; set; }
        public LocalizedValue<string> MetaKeywords { get; set; }
        public LocalizedValue<string> MetaDescription { get; set; }
        public LocalizedValue<string> MetaTitle { get; set; }
        public string SeName { get; set; }

        public PictureModel PictureModel { get; set; }
        public ProductSummaryModel FeaturedProducts { get; set; }
        public ProductSummaryModel Products { get; set; }

		public CatalogSearchResult SearchResult
		{
			get;
			set;
		}
	}
}

src/Presentation/SmartStore.Web/Models/Catalog/ManufacturerNavigationModel.cs
using System.Collections.Generic;
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ManufacturerNavigationModel : ModelBase
    {
        public ManufacturerNavigationModel()
        {
            this.Manufacturers = new List<ManufacturerBriefInfoModel>();
        }

        public IList<ManufacturerBriefInfoModel> Manufacturers { get; set; }
        
        public bool DisplayAllManufacturersLink { get; set; }

        public bool DisplayManufacturers { get; set; }

        public bool DisplayImages { get; set; }
    }

    public partial class ManufacturerBriefInfoModel : EntityModelBase
    {
        public LocalizedValue<string> Name { get; set; }

        public string SeName { get; set; }

        public string PictureUrl { get; set; }

		public int? PictureId { get; set; }

		public bool HasPicture { get; set; }

        public int DisplayOrder { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ManufacturerOverviewModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Media;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ManufacturerOverviewModel : EntityModelBase
    {
        public LocalizedValue<string> Name { get; set; }
        public LocalizedValue<string> Description { get; set; }
		public string SeName { get; set; }
		public PictureModel Picture { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Catalog/ProductSpecificationModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Catalog
{
    public partial class ProductSpecificationModel : ModelBase
    {
        public int SpecificationAttributeId { get; set; }
        public LocalizedValue<string> SpecificationAttributeName { get; set; }
        public LocalizedValue<string> SpecificationAttributeOption { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/AmazonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartStore.Web.Controllers
{
    public class AmazonController : Controller
    {
        // GET: Amazon
        public ActionResult Search()
        {
            return View();
        }
    }
}

src/Presentation/SmartStore.Web/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web.Mvc;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Media;
using SmartStore.Services;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Services.Search;
using SmartStore.Services.Security;
using SmartStore.Services.Seo;
using SmartStore.Services.Stores;
using SmartStore.Utilities;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Security;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Catalog;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Common;
using SmartStore.Web.Framework.UI;

namespace SmartStore.Web.Controllers
{
	public partial class CatalogController : PublicControllerBase
    {
		private readonly ICommonServices _services;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IProductService _productService;
        private readonly ICategoryTemplateService _categoryTemplateService;
        private readonly IManufacturerTemplateService _manufacturerTemplateService;
        private readonly ICurrencyService _currencyService;
        private readonly IPictureService _pictureService;
        private readonly IPriceFormatter _priceFormatter;
		private readonly IOrderReportService _orderReportService;
		private readonly IProductTagService _productTagService;
		private readonly IRecentlyViewedProductsService _recentlyViewedProductsService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IAclService _aclService;
		private readonly IStoreMappingService _storeMappingService;
		private readonly ICatalogSearchService _catalogSearchService;
		private readonly MediaSettings _mediaSettings;
        private readonly CatalogSettings _catalogSettings;
		private readonly ICompareProductsService _compareProductsService;
        private readonly Lazy<ILanguageService> _languageService;
        private readonly CatalogHelper _helper;
		private readonly IBreadcrumb _breadcrumb;

		public CatalogController(
			ICommonServices services,
			ICategoryService categoryService,
            IManufacturerService manufacturerService, 
			IProductService productService,
            ICategoryTemplateService categoryTemplateService,
            IManufacturerTemplateService manufacturerTemplateService,
			ICurrencyService currencyService,
			IOrderReportService orderReportService,
			IProductTagService productTagService,
			IRecentlyViewedProductsService recentlyViewedProductsService,
            IPictureService pictureService,
            IPriceFormatter priceFormatter,
            ISpecificationAttributeService specificationAttributeService,
			ICompareProductsService compareProductsService,
			IGenericAttributeService genericAttributeService,
			IAclService aclService,
			IStoreMappingService storeMappingService,
			ICatalogSearchService catalogSearchService,
			MediaSettings mediaSettings, 
			CatalogSettings catalogSettings,
            Lazy<ILanguageService> languageService,
            CatalogHelper helper,
			IBreadcrumb breadcrumb)
        {
			_services = services;
			_categoryService = categoryService;
            _manufacturerService = manufacturerService;
            _productService = productService;
            _categoryTemplateService = categoryTemplateService;
            _manufacturerTemplateService = manufacturerTemplateService;
            _currencyService = currencyService;
			_orderReportService = orderReportService;
			_productTagService = productTagService;
			_recentlyViewedProductsService = recentlyViewedProductsService;
			_compareProductsService = compareProductsService;
            _pictureService = pictureService;
            _priceFormatter = priceFormatter;
            _specificationAttributeService = specificationAttributeService;
            _genericAttributeService = genericAttributeService;
            _aclService = aclService;
			_storeMappingService = storeMappingService;
			_catalogSearchService = catalogSearchService;
            _mediaSettings = mediaSettings;
            _catalogSettings = catalogSettings;
            _languageService = languageService;
            _helper = helper;
			_breadcrumb = breadcrumb;
        }

        #region Categories

        [RequireHttpsByConfigAttribute(SslRequirement.No)]
        public ActionResult Category(int categoryId, CatalogSearchQuery query)
        {
			var category = _categoryService.GetCategoryById(categoryId);
            if (category == null || category.Deleted)
				return HttpNotFound();

            // Check whether the current user has a "Manage catalog" permission
            // It allows him to preview a category before publishing
            if (!category.Published && !_services.Permissions.Authorize(StandardPermissionProvider.ManageCatalog))
				return HttpNotFound();

            // ACL (access control list)
            if (!_aclService.Authorize(category))
				return HttpNotFound();

			// Store mapping
			if (!_storeMappingService.Authorize(category))
				return HttpNotFound();

			// 'Continue shopping' URL
			if (!_services.WorkContext.CurrentCustomer.IsSystemAccount)
			{
				_genericAttributeService.SaveAttribute(_services.WorkContext.CurrentCustomer,
					SystemCustomerAttributeNames.LastContinueShoppingPage,
					_services.WebHelper.GetThisPageUrl(false),
					_services.StoreContext.CurrentStore.Id);
			}

            var model = category.ToModel();

			_services.DisplayControl.Announce(category);

            // Category breadcrumb
			if (_catalogSettings.CategoryBreadcrumbEnabled)
			{
				_helper.GetCategoryBreadCrumb(category.Id, 0).Select(x => x.Value).Each(x => _breadcrumb.Track(x));
			}

			model.SubCategoryDisplayType = _catalogSettings.SubCategoryDisplayType;

			var customerRolesIds = _services.WorkContext.CurrentCustomer.CustomerRoles.Where(x => x.Active).Select(x => x.Id).ToList();
			var subCategories = _categoryService.GetAllCategoriesByParentCategoryId(categoryId);
			int pictureSize = _mediaSettings.CategoryThumbPictureSize;
			var allPictureInfos = _pictureService.GetPictureInfos(subCategories.Select(x => x.PictureId.GetValueOrDefault()));
			var fallbackType = _catalogSettings.HideCategoryDefaultPictures ? FallbackPictureType.NoFallback : FallbackPictureType.Entity;

			// subcategories
			model.SubCategories = subCategories
				.Select(x =>
                {
                    var subCatName = x.GetLocalized(y => y.Name);
                    var subCatModel = new CategoryModel.SubCategoryModel
                    {
                        Id = x.Id,
                        Name = subCatName,
                        SeName = x.GetSeName(),
                    };

					_services.DisplayControl.Announce(x);

					// prepare picture model
					var pictureInfo = allPictureInfos.Get(x.PictureId.GetValueOrDefault());

					subCatModel.PictureModel = new PictureModel
					{
						PictureId = pictureInfo?.Id ?? 0,
						Size = pictureSize,
						ImageUrl = _pictureService.GetUrl(pictureInfo, pictureSize, fallbackType),
						FullSizeImageUrl = _pictureService.GetUrl(pictureInfo, 0, FallbackPictureType.NoFallback),
						FullSizeImageWidth = pictureInfo?.Width,
						FullSizeImageHeight = pictureInfo?.Height,
						Title = string.Format(T("Media.Category.ImageLinkTitleFormat"), subCatName),
						AlternateText = string.Format(T("Media.Category.ImageAlternateTextFormat"), subCatName)
					};

                    return subCatModel;
                })
                .ToList();

			// Featured Products
			if (!_catalogSettings.IgnoreFeaturedProducts)
			{
				CatalogSearchResult featuredProductsResult = null;

				string cacheKey = ModelCacheEventConsumer.CATEGORY_HAS_FEATURED_PRODUCTS_KEY.FormatInvariant(categoryId, string.Join(",", customerRolesIds), _services.StoreContext.CurrentStore.Id);
				var hasFeaturedProductsCache = _services.Cache.Get<bool?>(cacheKey);

				var featuredProductsQuery = new CatalogSearchQuery()
					.VisibleOnly(_services.WorkContext.CurrentCustomer)
					.VisibleIndividuallyOnly(true)
					.WithCategoryIds(true, categoryId)
					.HasStoreId(_services.StoreContext.CurrentStore.Id)
					.WithLanguage(_services.WorkContext.WorkingLanguage)
					.WithCurrency(_services.WorkContext.WorkingCurrency);

				if (!hasFeaturedProductsCache.HasValue)
				{
					featuredProductsResult = _catalogSearchService.Search(featuredProductsQuery);
					hasFeaturedProductsCache = featuredProductsResult.TotalHitsCount > 0;
					_services.Cache.Put(cacheKey, hasFeaturedProductsCache, TimeSpan.FromHours(6));
				}

				if (hasFeaturedProductsCache.Value && featuredProductsResult == null)
				{
					featuredProductsResult = _catalogSearchService.Search(featuredProductsQuery);
				}

				if (featuredProductsResult != null)
				{
					var featuredProductsmappingSettings = _helper.GetBestFitProductSummaryMappingSettings(ProductSummaryViewMode.Grid);
					model.FeaturedProducts = _helper.MapProductSummaryModel(featuredProductsResult.Hits, featuredProductsmappingSettings);
				}
			}

			// Products
			int[] catIds = new int[] { categoryId };
			if (_catalogSettings.ShowProductsFromSubcategories)
			{
				// Include subcategories
				catIds = catIds.Concat(_helper.GetChildCategoryIds(categoryId)).ToArray();
			}

			query.WithCategoryIds(_catalogSettings.IncludeFeaturedProductsInNormalLists ? (bool?)null : false, catIds);

src/Presentation/SmartStore.Web/Views/Catalog/Partials/CatalogMenu.Navbar.cshtml
@model NavigationModel
@using SmartStore.Collections;
@{
	if (IsStoreClosed)
	{
		return;
	}

	var currentNavItem = Model.SelectedNode.IsLeaf && Model.SelectedNode.Parent != null ? Model.SelectedNode.Parent.Value.EntityId : Model.SelectedNode.Value.EntityId;
	var renderMoreItem = false;
	var rtl = WorkContext.WorkingLanguage.Rtl;
}
@functions {
	private string GetNodeLink(TreeNode<MenuItem> node)
	{
		return node.Value.GenerateUrl(this.Url);
	}

	private string GetCssClassForNode(TreeNode<MenuItem> node, NodePathState state)
	{
		var liClasses = new List<string>();

		liClasses.Add("nav-item");

		if (node.Depth <= 1 && node.HasChildren)
		{
			liClasses.Add(node.Depth > 0 ? "dropdown-submenu" : "dropdown");
		}

		if ((state & NodePathState.Expanded) == NodePathState.Expanded)
		{
			liClasses.Add("expanded");
		}

		if ((state & NodePathState.Selected) == NodePathState.Selected)
		{
			liClasses.Add("selected");
		}

		return liClasses.Count > 0 ? String.Join(" ", liClasses) : null;
	}
}
<div class="megamenu-nav megamenu-nav--prev @(rtl ? "omega" : "alpha")">
	<a href="#" class="megamenu-nav-btn btn btn-icon"><i class="fa fa-angle-left"></i></a>
</div>
<ul class="navbar-nav flex-row flex-nowrap"
	data-selected-menu-item="@currentNavItem"
	data-current-category-id="@CurrentCategoryId"
	data-current-product-id="@CurrentProductId"
	data-current-manufacturer-id="@CurrentManufacturerId">
	@{ Html.RenderWidget("mainmenu_before_first_item"); }
	@{ bool showHomebutton = true;}
	@foreach (var node in Model.Root.Children)
	{
		var item = node.Value;


		if (!item.Visible || node.GetMetadata<bool>("spare", false))
		{
			if (node.GetMetadata<bool>("spare", false))
			{
				renderMoreItem = true;
			}

			continue;
		}

		var itemUrl = GetNodeLink(node);
		var itemState = node.GetNodePathState(Model.Path);
		var isMegaMenuActive = node.GetMetadata<bool?>("IsMegaMenuActive", false);
		var isDropDownActive = isMegaMenuActive == null ? true : (bool)isMegaMenuActive;
		if (showHomebutton)
		{
			<li class='nav-item' id="main-nav-item-2" data-id="2">
				<a href="./" class="nav-link">
					<span>Home</span>
				</a>
			</li>
			<li class='nav-item' id="main-nav-item-2" data-id="2">
				@*<a asp-controller="Amazon" asp-action="Search">About User Information</a>*@

				@Html.ActionLink("Amazon search", "Search",
		new { controller = "Amazon"},
		new { @class = "nav-link" })
			</li>
			showHomebutton = false;
		}

		<li class='@(GetCssClassForNode(node, itemState))' id="main-nav-item-@item.EntityId" data-id="@item.EntityId">
			@*@if (showHomebutton)
				{
					<a href="./" class="nav-link">
						<span>Home</span>
					</a>

					showHomebutton = false;
				}*@
			@if (node.HasChildren && isDropDownActive)
			{
				<a href="@itemUrl" class="nav-link dropdown-toggle" aria-expanded="false" data-target="#dropdown-menu-@item.EntityId">
					<span @Html.Attr("dir", item.Rtl ? "rtl" : "ltr", item.Rtl != WorkContext.WorkingLanguage.Rtl)>@item.Text</span>
				</a>
			}
			else
			{
				<a href="@itemUrl" class="nav-link">
					<span @Html.Attr("dir", item.Rtl ? "rtl" : "ltr", item.Rtl != WorkContext.WorkingLanguage.Rtl)>@item.Text</span>
				</a>
			}
			@if (!String.IsNullOrEmpty(item.BadgeText))
			{
				<label class="badge badge-@item.BadgeStyle.ToString().ToLower()">@item.BadgeText</label>
			}
		</li>
	}
	@if (renderMoreItem)
	{
		<li class="nav-item dropdown" id="main-nav-item--1" data-id="-1">
			<a href="#" class="nav-link dropdown-toggle" aria-expanded="false" data-target="#dropdown-menu--1">
				@T("CatalogMenu.MoreLink")
			</a>
		</li>
	}
	@{ Html.RenderWidget("mainmenu_after_last_item"); }
</ul>
<div class="megamenu-nav megamenu-nav--next @(rtl ? "alpha" : "omega")">
	<a href="#" class="megamenu-nav-btn btn btn-icon"><i class="fa fa-angle-right"></i></a>
</div>

src/Presentation/SmartStore.Web/Views/Catalog/Partials/CatalogMenu.cshtml
@model NavigationModel
@using SmartStore.Collections;

@{
    Layout = "";

    var cutOffItems = Model.Root.Children
        .Where(x => x.Value.Id == null && x.GetMetadata<bool>("spare", false))
        .ToList();
}

<div class="megamenu simple">
    @{ Html.RenderPartial("CatalogMenu.Navbar", Model); }
</div>

<div class="megamenu-dropdown-container simple">
    @foreach (var node in Model.Root.Children)
    {
        <div id="dropdown-menu-@node.Value.EntityId" data-id="@node.Value.EntityId">
            @CreateDrilldownMenu(node.Children, true)
        </div>
    }

    @if (cutOffItems.Count > 0)
    {
        <div id="dropdown-menu--1" data-id="-1">
            @CreateDrilldownMenu(cutOffItems, true)
        </div>
    }
</div>

@helper CreateDrilldownMenu(IEnumerable<TreeNode<MenuItem>> nodes, bool isRoot)
{
    if (isRoot)
    {
        @Html.Raw("<div class='dropdown-menu'>")
    }
    
    foreach (var node in nodes)
	{
		var item = node.Value;

		if (!item.Visible)
		{
			continue;
		}
		
		var itemUrl = item.GenerateUrl(this.Url);
		var itemState = node.GetNodePathState(Model.Path);
		
        <a class='dropdown-item@((itemState & NodePathState.Selected) == NodePathState.Selected ? " selected" : "")' 
           href="@itemUrl" id="dropdown-item-@item.EntityId" data-id="@item.EntityId">
            <span @Html.Attr("dir", item.Rtl ? "rtl" : "ltr", item.Rtl != WorkContext.WorkingLanguage.Rtl)>@item.Text</span>
        </a>
    }
    
    if (isRoot)
    {
        @Html.Raw("</div>")
    }
}

<script type="text/javascript">
    $(function () {
        $(".megamenu-container").megaMenu();
    });
</script>    

src/Presentation/SmartStore.Web/Views/Catalog/Partials/OffCanvasCompare.cshtml
@model ProductSummaryModel

@using SmartStore.Web.Models.Catalog;

<div class="offcanvas-cart-body offcanvas-scrollable">
    @if (Model.Items.Count == 0)
    {
        <div class="no-items">
            <h4 class="no-item-title">
                @T("ShoppingCart.Mini.EmptyCompare.Title")
            </h4>
            <p class="no-item-icon">
                <i class="fa fa-retweet fa-4x"></i>
            </p>
            <p class="no-item-info text-muted">
                @T("ShoppingCart.Mini.EmptyCompare.Info", "fa fa-lg fa-retweet")
            </p>
        </div>
    }

    @if (Model.Items.Count > 0)
    {
        <div class="offcanvas-cart-items">
            @foreach (var item in Model.Items)
            {
                <div class="offcanvas-cart-item">
                    <div class="row sm-gutters">
                        <div class="col col-alpha">
                            @if (item.Picture.ImageUrl.HasValue())
                            {
                                <a class="img-center-container" href="@Url.RouteUrl("Product", new { SeName = item.SeName })" title="@item.Picture.Title">
                                    <img alt="@item.Picture.AlternateText" src="@item.Picture.ImageUrl" title="@item.Picture.Title" />
                                </a>
                            }
                        </div>

                        <div class="col col-data">
                            <a class="name font-weight-medium" href="@Url.RouteUrl("Product", new { SeName = item.SeName })" title="@item.Name">
								<span @Html.LanguageAttributes(item.Name)>@item.Name</span>
							</a>
                            <div @Html.LanguageAttributes(item.ShortDescription) class="short-desc text-muted">
                                @Html.Raw(item.ShortDescription.Value.Truncate(120, "..."))
                            </div>

                            <div class="d-flex align-items-center sm-gutters mt-2">
                                <div class="col">
                                    <span class="price unit-price">
                                        @item.Price.Price
                                    </span>
                                </div>
                                <div class="col-auto text-nowrap">
                                    <a class="btn btn-secondary btn-to-danger btn-sm btn-icon remove ajax-cart-link"
                                       href="#"
                                       rel="nofollow"
                                       data-href='@Url.Action("RemoveProductFromCompare", "Catalog", new { id = item.Id })'
                                       data-type="compare"
                                       data-action="remove"
                                       title='@T("Common.Remove")'>
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @{ Html.RenderWidget("offcanvas_compare_items_after"); }
        </div>
    }
</div>

@if (Model.Items.Count > 0)
{
    <div class="offcanvas-cart-footer">
        <div class="offcanvas-cart-footer-row sm-gutters">
            <div class="col">
                <a class="btn btn-clear btn-block btn-action" href="@Url.RouteUrl("CompareProducts")">
                    <i class="fa fa-check"></i>
                    <span>@T("Products.Compare.CompareNow")</span>
                </a>
            </div>
            <div class="col">
                <a class="btn btn-clear btn-block btn-action ajax-cart-link" href="#" data-href="@Url.Action("ClearCompareList")" rel="nofollow" data-type="compare" data-action="remove">
                    <i class="fa fa-trash"></i>
                    <span>@T("Products.Compare.Clear")</span>
                </a>
            </div>
        </div>
    </div>
}